import pyspark.sql.types as T

all_columns = {
    "acpdisp_1": T.StringType(),
    "acpdisp_2": T.StringType(),
    "acpdisp_3": T.StringType(),
    "acpdisp_4": T.StringType(),
    "acpdisp_5": T.StringType(),
    "acpdisp_6": T.StringType(),
    "acpdisp_7": T.StringType(),
    "acpdisp_8": T.StringType(),
    "acpdisp_9": T.StringType(),
    "acpdqind_1": T.StringType(),
    "acpdqind_2": T.StringType(),
    "acpdqind_3": T.StringType(),
    "acpdqind_4": T.StringType(),
    "acpdqind_5": T.StringType(),
    "acpdqind_6": T.StringType(),
    "acpdqind_7": T.StringType(),
    "acpdqind_8": T.StringType(),
    "acpdqind_9": T.StringType(),
    "acpend_1": T.DateType(),
    "acpend_2": T.DateType(),
    "acpend_3": T.DateType(),
    "acpend_4": T.DateType(),
    "acpend_5": T.DateType(),
    "acpend_6": T.DateType(),
    "acpend_7": T.DateType(),
    "acpend_8": T.DateType(),
    "acpend_9": T.DateType(),
    "acploc_1": T.StringType(),
    "acploc_2": T.StringType(),
    "acploc_3": T.StringType(),
    "acploc_4": T.StringType(),
    "acploc_5": T.StringType(),
    "acploc_6": T.StringType(),
    "acploc_7": T.StringType(),
    "acploc_8": T.StringType(),
    "acploc_9": T.StringType(),
    "acpn_1": T.IntegerType(),
    "acpn_2": T.IntegerType(),
    "acpn_3": T.IntegerType(),
    "acpn_4": T.IntegerType(),
    "acpn_5": T.IntegerType(),
    "acpn_6": T.IntegerType(),
    "acpn_7": T.IntegerType(),
    "acpn_8": T.IntegerType(),
    "acpn_9": T.IntegerType(),
    "acpout_1": T.StringType(),
    "acpout_2": T.StringType(),
    "acpout_3": T.StringType(),
    "acpout_4": T.StringType(),
    "acpout_5": T.StringType(),
    "acpout_6": T.StringType(),
    "acpout_7": T.StringType(),
    "acpout_8": T.StringType(),
    "acpout_9": T.StringType(),
    "acpplan_1": T.StringType(),
    "acpplan_2": T.StringType(),
    "acpplan_3": T.StringType(),
    "acpplan_4": T.StringType(),
    "acpplan_5": T.StringType(),
    "acpplan_6": T.StringType(),
    "acpplan_7": T.StringType(),
    "acpplan_8": T.StringType(),
    "acpplan_9": T.StringType(),
    "acpsour_1": T.StringType(),
    "acpsour_2": T.StringType(),
    "acpsour_3": T.StringType(),
    "acpsour_4": T.StringType(),
    "acpsour_5": T.StringType(),
    "acpsour_6": T.StringType(),
    "acpsour_7": T.StringType(),
    "acpsour_8": T.StringType(),
    "acpsour_9": T.StringType(),
    "acpspef_1": T.StringType(),
    "acpspef_2": T.StringType(),
    "acpspef_3": T.StringType(),
    "acpspef_4": T.StringType(),
    "acpspef_5": T.StringType(),
    "acpspef_6": T.StringType(),
    "acpspef_7": T.StringType(),
    "acpspef_8": T.StringType(),
    "acpspef_9": T.StringType(),
    "acpstar_1": T.DateType(),
    "acpstar_2": T.DateType(),
    "acpstar_3": T.DateType(),
    "acpstar_4": T.DateType(),
    "acpstar_5": T.DateType(),
    "acpstar_6": T.DateType(),
    "acpstar_7": T.DateType(),
    "acpstar_8": T.DateType(),
    "acpstar_9": T.DateType(),
    "acscflag": T.IntegerType(),
    "activage": T.IntegerType(),
    "adm_cfl": T.IntegerType(),
    "admiage": T.IntegerType(),
    "admidate": T.DateType(),
    "admimeth": T.StringType(),
    "admincat": T.StringType(),
    "admincatst": T.StringType(),
    "admisorc": T.StringType(),
    "admistat": T.StringType(),
    "aekey": T.StringType(),
    "alcdiag": T.StringType(),
    "alcdiag_4": T.StringType(),
    "alcfrac": T.FloatType(),
    "anagest": T.IntegerType(),
    "anasdate": T.DateType(),
    "antedur": T.IntegerType(),
    "at_gp_practice": T.StringType(),
    "at_residence": T.StringType(),
    "at_treatment": T.StringType(),
    "bedyear": T.IntegerType(),
    "biresus_1": T.StringType(),
    "biresus_2": T.StringType(),
    "biresus_3": T.StringType(),
    "biresus_4": T.StringType(),
    "biresus_5": T.StringType(),
    "biresus_6": T.StringType(),
    "biresus_7": T.StringType(),
    "biresus_8": T.StringType(),
    "biresus_9": T.StringType(),
    "birordr_1": T.StringType(),
    "birordr_2": T.StringType(),
    "birordr_3": T.StringType(),
    "birordr_4": T.StringType(),
    "birordr_5": T.StringType(),
    "birordr_6": T.StringType(),
    "birordr_7": T.StringType(),
    "birordr_8": T.StringType(),
    "birordr_9": T.StringType(),
    "birstat_1": T.StringType(),
    "birstat_2": T.StringType(),
    "birstat_3": T.StringType(),
    "birstat_4": T.StringType(),
    "birstat_5": T.StringType(),
    "birstat_6": T.StringType(),
    "birstat_7": T.StringType(),
    "birstat_8": T.StringType(),
    "birstat_9": T.StringType(),
    "birweit_1": T.IntegerType(),
    "birweit_2": T.IntegerType(),
    "birweit_3": T.IntegerType(),
    "birweit_4": T.IntegerType(),
    "birweit_5": T.IntegerType(),
    "birweit_6": T.IntegerType(),
    "birweit_7": T.IntegerType(),
    "birweit_8": T.IntegerType(),
    "birweit_9": T.IntegerType(),
    "cannet": T.StringType(),
    "canreg": T.StringType(),
    "carersi": T.StringType(),
    "category": T.StringType(),
    "cause": T.StringType(),
    "cause3": T.StringType(),
    "cause4": T.StringType(),
    "cause_3": T.StringType(),
    "cause_4": T.StringType(),
    "ccg_gp_practice": T.StringType(),
    "ccg_residence": T.StringType(),
    "ccg_responsibility": T.StringType(),
    "ccg_responsibility_origin": T.StringType(),
    "ccg_treatment": T.StringType(),
    "ccg_treatment_origin": T.StringType(),
    "cdsextdate": T.DateType(),
    "cdsverprotid": T.StringType(),
    "cdsversion": T.StringType(),
    "cendur": T.IntegerType(),
    "censage": T.IntegerType(),
    "censtat": T.StringType(),
    "cenward": T.StringType(),
    "classpat": T.StringType(),
    "cr_gp_practice": T.StringType(),
    "cr_residence": T.StringType(),
    "cr_treatment": T.StringType(),
    "csnum": T.StringType(),
    "currward": T.StringType(),
    "currward_ons": T.StringType(),
    "delchang": T.StringType(),
    "delinten": T.StringType(),
    "delmeth_1": T.StringType(),
    "delmeth_2": T.StringType(),
    "delmeth_3": T.StringType(),
    "delmeth_4": T.StringType(),
    "delmeth_5": T.StringType(),
    "delmeth_6": T.StringType(),
    "delmeth_7": T.StringType(),
    "delmeth_8": T.StringType(),
    "delmeth_9": T.StringType(),
    "delmeth_d": T.StringType(),
    "delonset": T.IntegerType(),
    "delplac_1": T.StringType(),
    "delplac_2": T.StringType(),
    "delplac_3": T.StringType(),
    "delplac_4": T.StringType(),
    "delplac_5": T.StringType(),
    "delplac_6": T.StringType(),
    "delplac_7": T.StringType(),
    "delplac_8": T.StringType(),
    "delplac_9": T.StringType(),
    "delposan": T.StringType(),
    "delprean": T.StringType(),
    "delstat_1": T.StringType(),
    "delstat_2": T.StringType(),
    "delstat_3": T.StringType(),
    "delstat_4": T.StringType(),
    "delstat_5": T.StringType(),
    "delstat_6": T.StringType(),
    "delstat_7": T.StringType(),
    "delstat_8": T.StringType(),
    "delstat_9": T.StringType(),
    "depdays_1": T.IntegerType(),
    "depdays_2": T.IntegerType(),
    "depdays_3": T.IntegerType(),
    "depdays_4": T.IntegerType(),
    "depdays_5": T.IntegerType(),
    "depdays_6": T.IntegerType(),
    "depdays_7": T.IntegerType(),
    "depdays_8": T.IntegerType(),
    "depdays_9": T.IntegerType(),
    "det_cfl": T.IntegerType(),
    "detdur": T.IntegerType(),
    "detndate": T.DateType(),
    "diag3_01": T.StringType(),
    "diag4_01": T.StringType(),
    "diag_01": T.StringType(),
    "diag_02": T.StringType(),
    "diag_03": T.StringType(),
    "diag_04": T.StringType(),
    "diag_05": T.StringType(),
    "diag_06": T.StringType(),
    "diag_07": T.StringType(),
    "diag_08": T.StringType(),
    "diag_09": T.StringType(),
    "diag_10": T.StringType(),
    "diag_11": T.StringType(),
    "diag_12": T.StringType(),
    "diag_13": T.StringType(),
    "diag_14": T.StringType(),
    "diag_15": T.StringType(),
    "diag_16": T.StringType(),
    "diag_17": T.StringType(),
    "diag_18": T.StringType(),
    "diag_19": T.StringType(),
    "diag_20": T.StringType(),
    "diag_count": T.IntegerType(),
    "dis_cfl": T.IntegerType(),
    "disdate": T.DateType(),
    "disdest": T.StringType(),
    "dismeth": T.StringType(),
    "disreadydate": T.DateType(),
    "dob_cfl": T.IntegerType(),
    "domproc": T.StringType(),
    "earldatoff": T.DateType(),
    "elec_cfl": T.IntegerType(),
    "elecdate": T.DateType(),
    "elecdur": T.IntegerType(),
    "elecdur_calc": T.IntegerType(),
    "encrypted_hesid": T.StringType(),
    "endage": T.IntegerType(),
    "epidur": T.IntegerType(),
    "epie_cfl": T.IntegerType(),
    "epiend": T.DateType(),
    "epikey": T.StringType(),
    "epiorder": T.IntegerType(),
    "epis_cfl": T.IntegerType(),
    "epistart": T.DateType(),
    "epistat": T.IntegerType(),
    "epitype": T.IntegerType(),
    "ethnos": T.StringType(),
    "ethraw": T.StringType(),
    "fae": T.IntegerType(),
    "fae_emergency": T.IntegerType(),
    "fce": T.IntegerType(),
    "fde": T.IntegerType(),
    "firstreg": T.StringType(),
    "fyear": T.StringType(),
    "gestat_1": T.IntegerType(),
    "gestat_2": T.IntegerType(),
    "gestat_3": T.IntegerType(),
    "gestat_4": T.IntegerType(),
    "gestat_5": T.IntegerType(),
    "gestat_6": T.IntegerType(),
    "gestat_7": T.IntegerType(),
    "gestat_8": T.IntegerType(),
    "gestat_9": T.IntegerType(),
    "gortreat": T.StringType(),
    "gpprac": T.StringType(),
    "gppracha": T.StringType(),
    "gppracro": T.StringType(),
    "gpprpct": T.StringType(),
    "gpprstha": T.StringType(),
    "hatreat": T.StringType(),
    "hneoind": T.StringType(),
    "hrglate35": T.StringType(),
    "hrgnhs": T.StringType(),
    "hrgnhsvn": T.StringType(),
    "imd04": T.FloatType(),
    "imd04_decile": T.StringType(),
    "imd04c": T.FloatType(),
    "imd04ed": T.FloatType(),
    "imd04em": T.FloatType(),
    "imd04hd": T.FloatType(),
    "imd04hs": T.FloatType(),
    "imd04i": T.FloatType(),
    "imd04ia": T.FloatType(),
    "imd04ic": T.FloatType(),
    "imd04le": T.FloatType(),
    "imd04rk": T.FloatType(),
    "intdays_1": T.IntegerType(),
    "intdays_2": T.IntegerType(),
    "intdays_3": T.IntegerType(),
    "intdays_4": T.IntegerType(),
    "intdays_5": T.IntegerType(),
    "intdays_6": T.IntegerType(),
    "intdays_7": T.IntegerType(),
    "intdays_8": T.IntegerType(),
    "intdays_9": T.IntegerType(),
    "intmanig": T.StringType(),
    "lsoa01": T.StringType(),
    "lsoa11": T.StringType(),
    "mainspef": T.StringType(),
    "marstat": T.StringType(),
    "matage": T.IntegerType(),
    "maternity_episode_type": T.StringType(),
    "mentcat": T.StringType(),
    "msoa01": T.StringType(),
    "msoa11": T.StringType(),
    "mydob": T.StringType(),
    "neocare": T.StringType(),
    "neodur": T.IntegerType(),
    "newnhsno_check": T.StringType(),
    "nhsnoind": T.StringType(),
    "numacp": T.IntegerType(),
    "numbaby": T.StringType(),
    "numpreg": T.IntegerType(),
    "numtailb": T.IntegerType(),
    "oacode6": T.StringType(),
    "opcs43": T.StringType(),
    "opdate_01": T.DateType(),
    "opdate_02": T.DateType(),
    "opdate_03": T.DateType(),
    "opdate_04": T.DateType(),
    "opdate_05": T.DateType(),
    "opdate_06": T.DateType(),
    "opdate_07": T.DateType(),
    "opdate_08": T.DateType(),
    "opdate_09": T.DateType(),
    "opdate_10": T.DateType(),
    "opdate_11": T.DateType(),
    "opdate_12": T.DateType(),
    "opdate_13": T.DateType(),
    "opdate_14": T.DateType(),
    "opdate_15": T.DateType(),
    "opdate_16": T.DateType(),
    "opdate_17": T.DateType(),
    "opdate_18": T.DateType(),
    "opdate_19": T.DateType(),
    "opdate_20": T.DateType(),
    "opdate_21": T.DateType(),
    "opdate_22": T.DateType(),
    "opdate_23": T.DateType(),
    "opdate_24": T.DateType(),
    "operstat": T.StringType(),
    "opertn3_01": T.StringType(),
    "opertn_01": T.StringType(),
    "opertn_02": T.StringType(),
    "opertn_03": T.StringType(),
    "opertn_04": T.StringType(),
    "opertn_05": T.StringType(),
    "opertn_06": T.StringType(),
    "opertn_07": T.StringType(),
    "opertn_08": T.StringType(),
    "opertn_09": T.StringType(),
    "opertn_10": T.StringType(),
    "opertn_11": T.StringType(),
    "opertn_12": T.StringType(),
    "opertn_13": T.StringType(),
    "opertn_14": T.StringType(),
    "opertn_15": T.StringType(),
    "opertn_16": T.StringType(),
    "opertn_17": T.StringType(),
    "opertn_18": T.StringType(),
    "opertn_19": T.StringType(),
    "opertn_20": T.StringType(),
    "opertn_21": T.StringType(),
    "opertn_22": T.StringType(),
    "opertn_23": T.StringType(),
    "opertn_24": T.StringType(),
    "opertn_count": T.IntegerType(),
    "orgpppid": T.StringType(),
    "orgsup_1": T.IntegerType(),
    "orgsup_2": T.IntegerType(),
    "orgsup_3": T.IntegerType(),
    "orgsup_4": T.IntegerType(),
    "orgsup_5": T.IntegerType(),
    "orgsup_6": T.IntegerType(),
    "orgsup_7": T.IntegerType(),
    "orgsup_8": T.IntegerType(),
    "orgsup_9": T.IntegerType(),
    "partyear": T.IntegerType(),
    "pcfound": T.StringType(),
    "pcgcode": T.StringType(),
    "pcgorig": T.StringType(),
    "pcon": T.StringType(),
    "pcon_ons": T.StringType(),
    "pconsult": T.StringType(),
    "pctcode": T.StringType(),
    "pctcode02": T.StringType(),
    "pctcode06": T.StringType(),
    "pctnhs": T.StringType(),
    "pctorig": T.StringType(),
    "pctorig02": T.StringType(),
    "pctorig06": T.StringType(),
    "pcttreat": T.StringType(),
    "person_id_deid": T.StringType(),
    "posopdur": T.IntegerType(),
    "postdist": T.StringType(),
    "postdur": T.IntegerType(),
    "preferer": T.StringType(),
    "preggmp": T.StringType(),
    "preopdur": T.IntegerType(),
    "primercp": T.StringType(),
    "procode": T.StringType(),
    "procode3": T.StringType(),
    "procode5": T.StringType(),
    "procodet": T.StringType(),
    "protype": T.StringType(),
    "provspno": T.LongType(),
    "provspnops": T.StringType(),
    "purcode": T.StringType(),
    "purro": T.StringType(),
    "purstha": T.StringType(),
    "purval": T.StringType(),
    "referorg": T.StringType(),
    "rescty": T.StringType(),
    "rescty_ons": T.StringType(),
    "resgor": T.StringType(),
    "resgor_ons": T.StringType(),
    "resha": T.StringType(),
    "resladst": T.StringType(),
    "resladst_currward": T.StringType(),
    "resladst_ons": T.StringType(),
    "respct": T.StringType(),
    "respct02": T.StringType(),
    "respct06": T.StringType(),
    "respct_his": T.StringType(),
    "resro": T.StringType(),
    "resstha": T.StringType(),
    "resstha02": T.StringType(),
    "resstha06": T.StringType(),
    "resstha_his": T.StringType(),
    "rotreat": T.StringType(),
    "rttperend": T.DateType(),
    "rttperstart": T.DateType(),
    "rttperstat": T.StringType(),
    "rururb_ind": T.StringType(),
    "sender": T.StringType(),
    "sex": T.StringType(),
    "sexbaby_1": T.StringType(),
    "sexbaby_2": T.StringType(),
    "sexbaby_3": T.StringType(),
    "sexbaby_4": T.StringType(),
    "sexbaby_5": T.StringType(),
    "sexbaby_6": T.StringType(),
    "sexbaby_7": T.StringType(),
    "sexbaby_8": T.StringType(),
    "sexbaby_9": T.StringType(),
    "sitetret": T.StringType(),
    "soal": T.StringType(),
    "soam": T.StringType(),
    "spelbgin": T.IntegerType(),
    "speldur": T.IntegerType(),
    "spelend": T.StringType(),
    "startage": T.IntegerType(),
    "startage_calc": T.FloatType(),
    "sthatret": T.StringType(),
    "subdate": T.DateType(),
    "suscorehrg": T.StringType(),
    "sushrg": T.StringType(),
    "sushrgvers": T.StringType(),
    "suslddate": T.DateType(),
    "susrecid": T.StringType(),
    "susspellid": T.StringType(),
    "tretspef": T.StringType(),
    "vind": T.StringType(),
    "waitdays": T.IntegerType(),
    "waitlist": T.IntegerType(),
    "ward91": T.StringType(),
    "wardstrt": T.StringType(),
    "well_baby_ind": T.StringType(),
}

columns = {}

# 1989/90 to 1996/97
for i in range(1989, 1997):
    cols = [
        "category",
        "admincat",
        "endage",
        "startage",
        "neodur",
        "mydob",
        "dob_cfl",
        "ethnos",
        "encrypted_hesid",
        "postdist",
        "sex",
        "admidate",
        "adm_cfl",
        "elecdate",
        "elec_cfl",
        "admimeth",
        "admisorc",
        "firstreg",
        "elecdur",
        "disdate",
        "dis_cfl",
        "disdest",
        "dismeth",
        "bedyear",
        "spelbgin",
        "epiend",
        "epistart",
        "speldur",
        "spelend",
        "epidur",
        "epiorder",
        "epie_cfl",
        "epis_cfl",
        "epistat",
        "epitype",
        "provspno",
        "wardstrt",
        "disreadydate",
        "diag_01",
        "diag_02",
        "diag_03",
        "diag_04",
        "diag_05",
        "diag_06",
        "diag_07",
        "diag_08",
        "diag_09",
        "diag_10",
        "diag_11",
        "diag_12",
        "diag_13",
        "diag_14",
        "diag_15",
        "diag_16",
        "diag_17",
        "diag_18",
        "diag_19",
        "diag_20",
        "diag3_01",
        "diag4_01",
        "cause",
        "cause4",
        "cause3",
        "opertn_01",
        "opertn_02",
        "opertn_03",
        "opertn_04",
        "opertn_05",
        "opertn_06",
        "opertn_07",
        "opertn_08",
        "opertn_09",
        "opertn_10",
        "opertn_11",
        "opertn_12",
        "opertn_13",
        "opertn_14",
        "opertn_15",
        "opertn_16",
        "opertn_17",
        "opertn_18",
        "opertn_19",
        "opertn_20",
        "opertn_21",
        "opertn_22",
        "opertn_23",
        "opertn_24",
        "opertn3_01",
        "opdate_01",
        "opdate_02",
        "opdate_03",
        "opdate_04",
        "opdate_05",
        "opdate_06",
        "opdate_07",
        "opdate_08",
        "opdate_09",
        "opdate_10",
        "opdate_11",
        "opdate_12",
        "opdate_13",
        "opdate_14",
        "opdate_15",
        "opdate_16",
        "opdate_17",
        "opdate_18",
        "opdate_19",
        "opdate_20",
        "opdate_21",
        "opdate_22",
        "opdate_23",
        "opdate_24",
        "operstat",
        "posopdur",
        "preopdur",
        "classpat",
        "intmanig",
        "mainspef",
        "tretspef",
        "domproc",
        "hrglate35",
        "hrgnhs",
        "hrgnhsvn",
        "suscorehrg",
        "sushrg",
        "sushrgvers",
        "susspellid",
        "purcode",
        "purval",
        "purro",
        "purstha",
        "csnum",
        "gppracha",
        "pcgcode",
        "pctcode",
        "pctcode06",
        "gpprpct",
        "procode",
        "procode3",
        "procodet",
        "sitetret",
        "protype",
        "gppracro",
        "gpprstha",
        "oacode6",
        "rescty",
        "resladst",
        "resladst_currward",
        "ward91",
        "resgor",
        "gortreat",
        "resha",
        "hatreat",
        "pctnhs",
        "respct",
        "respct06",
        "resstha",
        "resstha06",
        "pcttreat",
        "rotreat",
        "resro",
        "sthatret",
        "lsoa01",
        "msoa01",
        "rururb_ind",
        "imd04c",
        "imd04ed",
        "imd04em",
        "imd04hd",
        "imd04hs",
        "imd04i",
        "imd04ia",
        "imd04ic",
        "imd04le",
        "imd04",
        "imd04rk",
        "imd04_decile",
        "gpprac",
        "pconsult",
        "preggmp",
        "preferer",
        "referorg",
        "acploc_1",
        "acploc_2",
        "acploc_3",
        "acploc_4",
        "acploc_5",
        "acploc_6",
        "acploc_7",
        "acploc_8",
        "acploc_9",
        "acpdqind_1",
        "acpdqind_2",
        "acpdqind_3",
        "acpdqind_4",
        "acpdqind_5",
        "acpdqind_6",
        "acpdqind_7",
        "acpdqind_8",
        "acpdqind_9",
        "acpdisp_1",
        "acpdisp_2",
        "acpdisp_3",
        "acpdisp_4",
        "acpdisp_5",
        "acpdisp_6",
        "acpdisp_7",
        "acpdisp_8",
        "acpdisp_9",
        "acpend_1",
        "acpend_2",
        "acpend_3",
        "acpend_4",
        "acpend_5",
        "acpend_6",
        "acpend_7",
        "acpend_8",
        "acpend_9",
        "acpplan_1",
        "acpplan_2",
        "acpplan_3",
        "acpplan_4",
        "acpplan_5",
        "acpplan_6",
        "acpplan_7",
        "acpplan_8",
        "acpplan_9",
        "acpn_1",
        "acpn_2",
        "acpn_3",
        "acpn_4",
        "acpn_5",
        "acpn_6",
        "acpn_7",
        "acpn_8",
        "acpn_9",
        "acpout_1",
        "acpout_2",
        "acpout_3",
        "acpout_4",
        "acpout_5",
        "acpout_6",
        "acpout_7",
        "acpout_8",
        "acpout_9",
        "acpsour_1",
        "acpsour_2",
        "acpsour_3",
        "acpsour_4",
        "acpsour_5",
        "acpsour_6",
        "acpsour_7",
        "acpsour_8",
        "acpsour_9",
        "acpspef_1",
        "acpspef_2",
        "acpspef_3",
        "acpspef_4",
        "acpspef_5",
        "acpspef_6",
        "acpspef_7",
        "acpspef_8",
        "acpspef_9",
        "acpstar_1",
        "acpstar_2",
        "acpstar_3",
        "acpstar_4",
        "acpstar_5",
        "acpstar_6",
        "acpstar_7",
        "acpstar_8",
        "acpstar_9",
        "depdays_1",
        "depdays_2",
        "depdays_3",
        "depdays_4",
        "depdays_5",
        "depdays_6",
        "depdays_7",
        "depdays_8",
        "depdays_9",
        "intdays_1",
        "intdays_2",
        "intdays_3",
        "intdays_4",
        "intdays_5",
        "intdays_6",
        "intdays_7",
        "intdays_8",
        "intdays_9",
        "numacp",
        "orgsup_1",
        "orgsup_2",
        "orgsup_3",
        "orgsup_4",
        "orgsup_5",
        "orgsup_6",
        "orgsup_7",
        "orgsup_8",
        "orgsup_9",
        "delprean",
        "delposan",
        "antedur",
        "birordr_1",
        "birordr_2",
        "birordr_3",
        "birordr_4",
        "birordr_5",
        "birordr_6",
        "birordr_7",
        "birordr_8",
        "birordr_9",
        "birweit_1",
        "birweit_2",
        "birweit_3",
        "birweit_4",
        "birweit_5",
        "birweit_6",
        "birweit_7",
        "birweit_8",
        "birweit_9",
        "delchang",
        "delmeth_1",
        "delmeth_2",
        "delmeth_3",
        "delmeth_4",
        "delmeth_5",
        "delmeth_6",
        "delmeth_7",
        "delmeth_8",
        "delmeth_9",
        "delplac_1",
        "delplac_2",
        "delplac_3",
        "delplac_4",
        "delplac_5",
        "delplac_6",
        "delplac_7",
        "delplac_8",
        "delplac_9",
        "delinten",
        "anasdate",
        "anagest",
        "gestat_1",
        "gestat_2",
        "gestat_3",
        "gestat_4",
        "gestat_5",
        "gestat_6",
        "gestat_7",
        "gestat_8",
        "gestat_9",
        "birstat_1",
        "birstat_2",
        "birstat_3",
        "birstat_4",
        "birstat_5",
        "birstat_6",
        "birstat_7",
        "birstat_8",
        "birstat_9",
        "delonset",
        "matage",
        "numbaby",
        "numpreg",
        "postdur",
        "biresus_1",
        "biresus_2",
        "biresus_3",
        "biresus_4",
        "biresus_5",
        "biresus_6",
        "biresus_7",
        "biresus_8",
        "biresus_9",
        "sexbaby_1",
        "sexbaby_2",
        "sexbaby_3",
        "sexbaby_4",
        "sexbaby_5",
        "sexbaby_6",
        "sexbaby_7",
        "sexbaby_8",
        "sexbaby_9",
        "delstat_1",
        "delstat_2",
        "delstat_3",
        "delstat_4",
        "delstat_5",
        "delstat_6",
        "delstat_7",
        "delstat_8",
        "delstat_9",
        "neocare",
        "well_baby_ind",
        "censage",
        "carersi",
        "detndate",
        "det_cfl",
        "cendur",
        "detdur",
        "marstat",
        "mentcat",
        "admistat",
        "censtat",
        "vind",
        "cenward",
        "subdate",
        "nhsnoind",
        "opcs43",
        "pcgorig",
        "pctorig",
        "pctorig06",
        "susrecid",
        "epikey",
    ]
    columns[i] = T.StructField([cols[c] for c in cols])
# 1997/98 to 2012/13
for i in range(1997, 2013):
    cols = [
        "category",
        "admincat",
        "endage",
        "startage",
        "neodur",
        "mydob",
        "dob_cfl",
        "ethnos",
        "encrypted_hesid",
        "postdist",
        "sex",
        "admidate",
        "adm_cfl",
        "elecdate",
        "elec_cfl",
        "admimeth",
        "admisorc",
        "firstreg",
        "elecdur",
        "disdate",
        "dis_cfl",
        "disdest",
        "dismeth",
        "bedyear",
        "spelbgin",
        "epiend",
        "epistart",
        "speldur",
        "spelend",
        "epidur",
        "epiorder",
        "epie_cfl",
        "epis_cfl",
        "epistat",
        "epitype",
        "provspno",
        "wardstrt",
        "disreadydate",
        "diag_01",
        "diag_02",
        "diag_03",
        "diag_04",
        "diag_05",
        "diag_06",
        "diag_07",
        "diag_08",
        "diag_09",
        "diag_10",
        "diag_11",
        "diag_12",
        "diag_13",
        "diag_14",
        "diag_15",
        "diag_16",
        "diag_17",
        "diag_18",
        "diag_19",
        "diag_20",
        "diag3_01",
        "diag4_01",
        "cause",
        "cause4",
        "cause3",
        "opertn_01",
        "opertn_02",
        "opertn_03",
        "opertn_04",
        "opertn_05",
        "opertn_06",
        "opertn_07",
        "opertn_08",
        "opertn_09",
        "opertn_10",
        "opertn_11",
        "opertn_12",
        "opertn_13",
        "opertn_14",
        "opertn_15",
        "opertn_16",
        "opertn_17",
        "opertn_18",
        "opertn_19",
        "opertn_20",
        "opertn_21",
        "opertn_22",
        "opertn_23",
        "opertn_24",
        "opertn3_01",
        "opdate_01",
        "opdate_02",
        "opdate_03",
        "opdate_04",
        "opdate_05",
        "opdate_06",
        "opdate_07",
        "opdate_08",
        "opdate_09",
        "opdate_10",
        "opdate_11",
        "opdate_12",
        "opdate_13",
        "opdate_14",
        "opdate_15",
        "opdate_16",
        "opdate_17",
        "opdate_18",
        "opdate_19",
        "opdate_20",
        "opdate_21",
        "opdate_22",
        "opdate_23",
        "opdate_24",
        "operstat",
        "posopdur",
        "preopdur",
        "classpat",
        "intmanig",
        "mainspef",
        "tretspef",
        "domproc",
        "hrglate35",
        "hrgnhs",
        "hrgnhsvn",
        "suscorehrg",
        "sushrg",
        "sushrgvers",
        "susspellid",
        "purcode",
        "purval",
        "purro",
        "purstha",
        "csnum",
        "gppracha",
        "pcgcode",
        "pctcode",
        "pctcode06",
        "gpprpct",
        "procode",
        "procode3",
        "procodet",
        "sitetret",
        "protype",
        "gppracro",
        "gpprstha",
        "oacode6",
        "rescty",
        "resladst",
        "resladst_currward",
        "ward91",
        "resgor",
        "gortreat",
        "resha",
        "hatreat",
        "pctnhs",
        "respct",
        "respct06",
        "resstha",
        "resstha06",
        "pcttreat",
        "rotreat",
        "resro",
        "sthatret",
        "lsoa01",
        "msoa01",
        "rururb_ind",
        "imd04c",
        "imd04ed",
        "imd04em",
        "imd04hd",
        "imd04hs",
        "imd04i",
        "imd04ia",
        "imd04ic",
        "imd04le",
        "imd04",
        "imd04rk",
        "imd04_decile",
        "gpprac",
        "pconsult",
        "preggmp",
        "preferer",
        "referorg",
        "acploc_1",
        "acploc_2",
        "acploc_3",
        "acploc_4",
        "acploc_5",
        "acploc_6",
        "acploc_7",
        "acploc_8",
        "acploc_9",
        "acpdqind_1",
        "acpdqind_2",
        "acpdqind_3",
        "acpdqind_4",
        "acpdqind_5",
        "acpdqind_6",
        "acpdqind_7",
        "acpdqind_8",
        "acpdqind_9",
        "acpdisp_1",
        "acpdisp_2",
        "acpdisp_3",
        "acpdisp_4",
        "acpdisp_5",
        "acpdisp_6",
        "acpdisp_7",
        "acpdisp_8",
        "acpdisp_9",
        "acpend_1",
        "acpend_2",
        "acpend_3",
        "acpend_4",
        "acpend_5",
        "acpend_6",
        "acpend_7",
        "acpend_8",
        "acpend_9",
        "acpplan_1",
        "acpplan_2",
        "acpplan_3",
        "acpplan_4",
        "acpplan_5",
        "acpplan_6",
        "acpplan_7",
        "acpplan_8",
        "acpplan_9",
        "acpn_1",
        "acpn_2",
        "acpn_3",
        "acpn_4",
        "acpn_5",
        "acpn_6",
        "acpn_7",
        "acpn_8",
        "acpn_9",
        "acpout_1",
        "acpout_2",
        "acpout_3",
        "acpout_4",
        "acpout_5",
        "acpout_6",
        "acpout_7",
        "acpout_8",
        "acpout_9",
        "acpsour_1",
        "acpsour_2",
        "acpsour_3",
        "acpsour_4",
        "acpsour_5",
        "acpsour_6",
        "acpsour_7",
        "acpsour_8",
        "acpsour_9",
        "acpspef_1",
        "acpspef_2",
        "acpspef_3",
        "acpspef_4",
        "acpspef_5",
        "acpspef_6",
        "acpspef_7",
        "acpspef_8",
        "acpspef_9",
        "acpstar_1",
        "acpstar_2",
        "acpstar_3",
        "acpstar_4",
        "acpstar_5",
        "acpstar_6",
        "acpstar_7",
        "acpstar_8",
        "acpstar_9",
        "depdays_1",
        "depdays_2",
        "depdays_3",
        "depdays_4",
        "depdays_5",
        "depdays_6",
        "depdays_7",
        "depdays_8",
        "depdays_9",
        "intdays_1",
        "intdays_2",
        "intdays_3",
        "intdays_4",
        "intdays_5",
        "intdays_6",
        "intdays_7",
        "intdays_8",
        "intdays_9",
        "numacp",
        "orgsup_1",
        "orgsup_2",
        "orgsup_3",
        "orgsup_4",
        "orgsup_5",
        "orgsup_6",
        "orgsup_7",
        "orgsup_8",
        "orgsup_9",
        "delprean",
        "delposan",
        "antedur",
        "birordr_1",
        "birordr_2",
        "birordr_3",
        "birordr_4",
        "birordr_5",
        "birordr_6",
        "birordr_7",
        "birordr_8",
        "birordr_9",
        "birweit_1",
        "birweit_2",
        "birweit_3",
        "birweit_4",
        "birweit_5",
        "birweit_6",
        "birweit_7",
        "birweit_8",
        "birweit_9",
        "delchang",
        "delmeth_1",
        "delmeth_2",
        "delmeth_3",
        "delmeth_4",
        "delmeth_5",
        "delmeth_6",
        "delmeth_7",
        "delmeth_8",
        "delmeth_9",
        "delplac_1",
        "delplac_2",
        "delplac_3",
        "delplac_4",
        "delplac_5",
        "delplac_6",
        "delplac_7",
        "delplac_8",
        "delplac_9",
        "delinten",
        "anasdate",
        "anagest",
        "gestat_1",
        "gestat_2",
        "gestat_3",
        "gestat_4",
        "gestat_5",
        "gestat_6",
        "gestat_7",
        "gestat_8",
        "gestat_9",
        "birstat_1",
        "birstat_2",
        "birstat_3",
        "birstat_4",
        "birstat_5",
        "birstat_6",
        "birstat_7",
        "birstat_8",
        "birstat_9",
        "delonset",
        "matage",
        "numbaby",
        "numpreg",
        "postdur",
        "biresus_1",
        "biresus_2",
        "biresus_3",
        "biresus_4",
        "biresus_5",
        "biresus_6",
        "biresus_7",
        "biresus_8",
        "biresus_9",
        "sexbaby_1",
        "sexbaby_2",
        "sexbaby_3",
        "sexbaby_4",
        "sexbaby_5",
        "sexbaby_6",
        "sexbaby_7",
        "sexbaby_8",
        "sexbaby_9",
        "delstat_1",
        "delstat_2",
        "delstat_3",
        "delstat_4",
        "delstat_5",
        "delstat_6",
        "delstat_7",
        "delstat_8",
        "delstat_9",
        "neocare",
        "well_baby_ind",
        "censage",
        "carersi",
        "detndate",
        "det_cfl",
        "cendur",
        "detdur",
        "marstat",
        "mentcat",
        "admistat",
        "censtat",
        "vind",
        "cenward",
        "subdate",
        "nhsnoind",
        "opcs43",
        "pcgorig",
        "pctorig",
        "pctorig06",
        "susrecid",
        "epikey",
    ]
    columns[i] = T.StructField([cols[c] for c in cols])

# 2013/14 to 2014/15
for i in range(2013, 2015):
    cols = [
        "category",
        "admincat",
        "endage",
        "startage",
        "neodur",
        "mydob",
        "dob_cfl",
        "ethnos",
        "encrypted_hesid",
        "postdist",
        "sex",
        "admidate",
        "adm_cfl",
        "elecdate",
        "elec_cfl",
        "admimeth",
        "admisorc",
        "firstreg",
        "elecdur",
        "disdate",
        "dis_cfl",
        "disdest",
        "dismeth",
        "bedyear",
        "spelbgin",
        "epiend",
        "epistart",
        "speldur",
        "spelend",
        "epidur",
        "epiorder",
        "epie_cfl",
        "epis_cfl",
        "epistat",
        "epitype",
        "provspno",
        "wardstrt",
        "disreadydate",
        "diag_01",
        "diag_02",
        "diag_03",
        "diag_04",
        "diag_05",
        "diag_06",
        "diag_07",
        "diag_08",
        "diag_09",
        "diag_10",
        "diag_11",
        "diag_12",
        "diag_13",
        "diag_14",
        "diag_15",
        "diag_16",
        "diag_17",
        "diag_18",
        "diag_19",
        "diag_20",
        "diag3_01",
        "diag4_01",
        "cause",
        "cause4",
        "cause3",
        "opertn_01",
        "opertn_02",
        "opertn_03",
        "opertn_04",
        "opertn_05",
        "opertn_06",
        "opertn_07",
        "opertn_08",
        "opertn_09",
        "opertn_10",
        "opertn_11",
        "opertn_12",
        "opertn_13",
        "opertn_14",
        "opertn_15",
        "opertn_16",
        "opertn_17",
        "opertn_18",
        "opertn_19",
        "opertn_20",
        "opertn_21",
        "opertn_22",
        "opertn_23",
        "opertn_24",
        "opertn3_01",
        "opdate_01",
        "opdate_02",
        "opdate_03",
        "opdate_04",
        "opdate_05",
        "opdate_06",
        "opdate_07",
        "opdate_08",
        "opdate_09",
        "opdate_10",
        "opdate_11",
        "opdate_12",
        "opdate_13",
        "opdate_14",
        "opdate_15",
        "opdate_16",
        "opdate_17",
        "opdate_18",
        "opdate_19",
        "opdate_20",
        "opdate_21",
        "opdate_22",
        "opdate_23",
        "opdate_24",
        "operstat",
        "posopdur",
        "preopdur",
        "classpat",
        "intmanig",
        "mainspef",
        "tretspef",
        "domproc",
        "hrglate35",
        "hrgnhs",
        "hrgnhsvn",
        "suscorehrg",
        "sushrg",
        "sushrgvers",
        "susspellid",
        "purcode",
        "purval",
        "purro",
        "purstha",
        "csnum",
        "gppracha",
        "pcgcode",
        "pctcode02",
        "pctcode06",
        "gpprpct",
        "procode",
        "procode3",
        "procodet",
        "sitetret",
        "protype",
        "gppracro",
        "gpprstha",
        "oacode6",
        "rescty",
        "resladst",
        "resladst_currward",
        "ward91",
        "resgor",
        "gortreat",
        "resha",
        "hatreat",
        "pctnhs",
        "respct02",
        "respct06",
        "resstha02",
        "resstha06",
        "pcttreat",
        "rotreat",
        "resro",
        "sthatret",
        "soal",
        "soam",
        "rururb_ind",
        "imd04c",
        "imd04ed",
        "imd04em",
        "imd04hd",
        "imd04hs",
        "imd04i",
        "imd04ia",
        "imd04ic",
        "imd04le",
        "imd04",
        "imd04rk",
        "imd04_decile",
        "gpprac",
        "pconsult",
        "preggmp",
        "preferer",
        "referorg",
        "acploc_1",
        "acploc_2",
        "acploc_3",
        "acploc_4",
        "acploc_5",
        "acploc_6",
        "acploc_7",
        "acploc_8",
        "acploc_9",
        "acpdqind_1",
        "acpdqind_2",
        "acpdqind_3",
        "acpdqind_4",
        "acpdqind_5",
        "acpdqind_6",
        "acpdqind_7",
        "acpdqind_8",
        "acpdqind_9",
        "acpdisp_1",
        "acpdisp_2",
        "acpdisp_3",
        "acpdisp_4",
        "acpdisp_5",
        "acpdisp_6",
        "acpdisp_7",
        "acpdisp_8",
        "acpdisp_9",
        "acpend_1",
        "acpend_2",
        "acpend_3",
        "acpend_4",
        "acpend_5",
        "acpend_6",
        "acpend_7",
        "acpend_8",
        "acpend_9",
        "acpplan_1",
        "acpplan_2",
        "acpplan_3",
        "acpplan_4",
        "acpplan_5",
        "acpplan_6",
        "acpplan_7",
        "acpplan_8",
        "acpplan_9",
        "acpn_1",
        "acpn_2",
        "acpn_3",
        "acpn_4",
        "acpn_5",
        "acpn_6",
        "acpn_7",
        "acpn_8",
        "acpn_9",
        "acpout_1",
        "acpout_2",
        "acpout_3",
        "acpout_4",
        "acpout_5",
        "acpout_6",
        "acpout_7",
        "acpout_8",
        "acpout_9",
        "acpsour_1",
        "acpsour_2",
        "acpsour_3",
        "acpsour_4",
        "acpsour_5",
        "acpsour_6",
        "acpsour_7",
        "acpsour_8",
        "acpsour_9",
        "acpspef_1",
        "acpspef_2",
        "acpspef_3",
        "acpspef_4",
        "acpspef_5",
        "acpspef_6",
        "acpspef_7",
        "acpspef_8",
        "acpspef_9",
        "acpstar_1",
        "acpstar_2",
        "acpstar_3",
        "acpstar_4",
        "acpstar_5",
        "acpstar_6",
        "acpstar_7",
        "acpstar_8",
        "acpstar_9",
        "depdays_1",
        "depdays_2",
        "depdays_3",
        "depdays_4",
        "depdays_5",
        "depdays_6",
        "depdays_7",
        "depdays_8",
        "depdays_9",
        "intdays_1",
        "intdays_2",
        "intdays_3",
        "intdays_4",
        "intdays_5",
        "intdays_6",
        "intdays_7",
        "intdays_8",
        "intdays_9",
        "numacp",
        "orgsup_1",
        "orgsup_2",
        "orgsup_3",
        "orgsup_4",
        "orgsup_5",
        "orgsup_6",
        "orgsup_7",
        "orgsup_8",
        "orgsup_9",
        "delprean",
        "delposan",
        "antedur",
        "birordr_1",
        "birordr_2",
        "birordr_3",
        "birordr_4",
        "birordr_5",
        "birordr_6",
        "birordr_7",
        "birordr_8",
        "birordr_9",
        "birweit_1",
        "birweit_2",
        "birweit_3",
        "birweit_4",
        "birweit_5",
        "birweit_6",
        "birweit_7",
        "birweit_8",
        "birweit_9",
        "delchang",
        "delmeth_1",
        "delmeth_2",
        "delmeth_3",
        "delmeth_4",
        "delmeth_5",
        "delmeth_6",
        "delmeth_7",
        "delmeth_8",
        "delmeth_9",
        "delplac_1",
        "delplac_2",
        "delplac_3",
        "delplac_4",
        "delplac_5",
        "delplac_6",
        "delplac_7",
        "delplac_8",
        "delplac_9",
        "delinten",
        "anasdate",
        "anagest",
        "gestat_1",
        "gestat_2",
        "gestat_3",
        "gestat_4",
        "gestat_5",
        "gestat_6",
        "gestat_7",
        "gestat_8",
        "gestat_9",
        "birstat_1",
        "birstat_2",
        "birstat_3",
        "birstat_4",
        "birstat_5",
        "birstat_6",
        "birstat_7",
        "birstat_8",
        "birstat_9",
        "delonset",
        "matage",
        "numbaby",
        "numpreg",
        "postdur",
        "biresus_1",
        "biresus_2",
        "biresus_3",
        "biresus_4",
        "biresus_5",
        "biresus_6",
        "biresus_7",
        "biresus_8",
        "biresus_9",
        "sexbaby_1",
        "sexbaby_2",
        "sexbaby_3",
        "sexbaby_4",
        "sexbaby_5",
        "sexbaby_6",
        "sexbaby_7",
        "sexbaby_8",
        "sexbaby_9",
        "delstat_1",
        "delstat_2",
        "delstat_3",
        "delstat_4",
        "delstat_5",
        "delstat_6",
        "delstat_7",
        "delstat_8",
        "delstat_9",
        "neocare",
        "well_baby_ind",
        "censage",
        "carersi",
        "detndate",
        "det_cfl",
        "cendur",
        "detdur",
        "marstat",
        "mentcat",
        "admistat",
        "censtat",
        "vind",
        "cenward",
        "subdate",
        "nhsnoind",
        "opcs43",
        "pcgorig",
        "pctorig02",
        "pctorig06",
        "susrecid",
        "epikey",
        "provspnops",
        "lsoa01",
        "msoa01",
    ]
    columns[i] = T.StructField([cols[c] for c in cols])

# 2015/16 to 2018/19
for i in range(2015, 2019):
    cols[i] = [
        "acscflag",
        "activage",
        "admiage",
        "admidate",
        "admimeth",
        "admincat",
        "admincatst",
        "admisorc",
        "admistat",
        "aekey",
        "alcdiag",
        "alcdiag_4",
        "alcfrac",
        "anagest",
        "anasdate",
        "antedur",
        "at_gp_practice",
        "at_residence",
        "at_treatment",
        "bedyear",
        "biresus_1",
        "biresus_2",
        "biresus_3",
        "biresus_4",
        "biresus_5",
        "biresus_6",
        "biresus_7",
        "biresus_8",
        "biresus_9",
        "birordr_1",
        "birordr_2",
        "birordr_3",
        "birordr_4",
        "birordr_5",
        "birordr_6",
        "birordr_7",
        "birordr_8",
        "birordr_9",
        "birstat_1",
        "birstat_2",
        "birstat_3",
        "birstat_4",
        "birstat_5",
        "birstat_6",
        "birstat_7",
        "birstat_8",
        "birstat_9",
        "birweit_1",
        "birweit_2",
        "birweit_3",
        "birweit_4",
        "birweit_5",
        "birweit_6",
        "birweit_7",
        "birweit_8",
        "birweit_9",
        "cannet",
        "canreg",
        "carersi",
        "cause",
        "cause_3",
        "cause_4",
        "ccg_gp_practice",
        "ccg_residence",
        "ccg_responsibility",
        "ccg_responsibility_origin",
        "ccg_treatment",
        "ccg_treatment_origin",
        "cdsextdate",
        "cdsverprotid",
        "cdsversion",
        "cendur",
        "censage",
        "censtat",
        "cenward",
        "classpat",
        "cr_gp_practice",
        "cr_residence",
        "cr_treatment",
        "csnum",
        "currward",
        "currward_ons",
        "delchang",
        "delinten",
        "delmeth_1",
        "delmeth_2",
        "delmeth_3",
        "delmeth_4",
        "delmeth_5",
        "delmeth_6",
        "delmeth_7",
        "delmeth_8",
        "delmeth_9",
        "delmeth_d",
        "delonset",
        "delplac_1",
        "delplac_2",
        "delplac_3",
        "delplac_4",
        "delplac_5",
        "delplac_6",
        "delplac_7",
        "delplac_8",
        "delplac_9",
        "delposan",
        "delprean",
        "delstat_1",
        "delstat_2",
        "delstat_3",
        "delstat_4",
        "delstat_5",
        "delstat_6",
        "delstat_7",
        "delstat_8",
        "delstat_9",
        "detdur",
        "detndate",
        "diag_01",
        "diag_02",
        "diag_03",
        "diag_04",
        "diag_05",
        "diag_06",
        "diag_07",
        "diag_08",
        "diag_09",
        "diag_10",
        "diag_11",
        "diag_12",
        "diag_13",
        "diag_14",
        "diag_15",
        "diag_16",
        "diag_17",
        "diag_18",
        "diag_19",
        "diag_20",
        "diag_count",
        "disdate",
        "disdest",
        "dismeth",
        "disreadydate",
        "earldatoff",
        "elecdate",
        "elecdur",
        "elecdur_calc",
        "encrypted_hesid",
        "endage",
        "epidur",
        "epiend",
        "epikey",
        "epiorder",
        "epistart",
        "epistat",
        "epitype",
        "ethnos",
        "ethraw",
        "fae",
        "fae_emergency",
        "fce",
        "fde",
        "firstreg",
        "fyear",
        "gestat_1",
        "gestat_2",
        "gestat_3",
        "gestat_4",
        "gestat_5",
        "gestat_6",
        "gestat_7",
        "gestat_8",
        "gestat_9",
        "gortreat",
        "gpprac",
        "gppracha",
        "gppracro",
        "gpprpct",
        "gpprstha",
        "hatreat",
        "hneoind",
        "imd04",
        "imd04_decile",
        "imd04c",
        "imd04ed",
        "imd04em",
        "imd04hd",
        "imd04hs",
        "imd04i",
        "imd04ia",
        "imd04ic",
        "imd04le",
        "imd04rk",
        "intmanig",
        "lsoa01",
        "lsoa11",
        "mainspef",
        "marstat",
        "matage",
        "maternity_episode_type",
        "mentcat",
        "msoa01",
        "msoa11",
        "mydob",
        "neocare",
        "neodur",
        "newnhsno_check",
        "nhsnoind",
        "numbaby",
        "numpreg",
        "numtailb",
        "oacode6",
        "opcs43",
        "opdate_01",
        "opdate_02",
        "opdate_03",
        "opdate_04",
        "opdate_05",
        "opdate_06",
        "opdate_07",
        "opdate_08",
        "opdate_09",
        "opdate_10",
        "opdate_11",
        "opdate_12",
        "opdate_13",
        "opdate_14",
        "opdate_15",
        "opdate_16",
        "opdate_17",
        "opdate_18",
        "opdate_19",
        "opdate_20",
        "opdate_21",
        "opdate_22",
        "opdate_23",
        "opdate_24",
        "operstat",
        "opertn_01",
        "opertn_02",
        "opertn_03",
        "opertn_04",
        "opertn_05",
        "opertn_06",
        "opertn_07",
        "opertn_08",
        "opertn_09",
        "opertn_10",
        "opertn_11",
        "opertn_12",
        "opertn_13",
        "opertn_14",
        "opertn_15",
        "opertn_16",
        "opertn_17",
        "opertn_18",
        "opertn_19",
        "opertn_20",
        "opertn_21",
        "opertn_22",
        "opertn_23",
        "opertn_24",
        "opertn_count",
        "orgpppid",
        "partyear",
        "pcfound",
        "pcon",
        "pcon_ons",
        "pconsult",
        "pctcode06",
        "pctnhs",
        "pctorig06",
        "pcttreat",
        "posopdur",
        "postdist",
        "postdur",
        "preferer",
        "preggmp",
        "preopdur",
        "primercp",
        "procode",
        "procode3",
        "procode5",
        "procodet",
        "protype",
        "provspnops",
        "purcode",
        "purval",
        "referorg",
        "rescty",
        "rescty_ons",
        "resgor",
        "resgor_ons",
        "resha",
        "resladst",
        "resladst_currward",
        "resladst_ons",
        "respct_his",
        "respct06",
        "resro",
        "resstha_his",
        "resstha06",
        "rotreat",
        "rttperend",
        "rttperstart",
        "rttperstat",
        "rururb_ind",
        "sender",
        "sex",
        "sexbaby_1",
        "sexbaby_2",
        "sexbaby_3",
        "sexbaby_4",
        "sexbaby_5",
        "sexbaby_6",
        "sexbaby_7",
        "sexbaby_8",
        "sexbaby_9",
        "sitetret",
        "spelbgin",
        "speldur",
        "spelend",
        "startage",
        "startage_calc",
        "sthatret",
        "subdate",
        "suscorehrg",
        "sushrg",
        "sushrgvers",
        "suslddate",
        "susrecid",
        "susspellid",
        "tretspef",
        "waitdays",
        "waitlist",
        "well_baby_ind",
    ]
    columns[i] = T.StructField([cols[c] for c in cols])

# 2019/20 to 2020/21
for i in range(2019, 2021):
    cols = [
        "person_id_deid",
        "acscflag",
        "activage",
        "admiage",
        "admidate",
        "admimeth",
        "admincat",
        "admincatst",
        "admisorc",
        "admistat",
        "aekey",
        "alcdiag",
        "alcdiag_4",
        "alcfrac",
        "anagest",
        "anasdate",
        "antedur",
        "at_gp_practice",
        "at_residence",
        "at_treatment",
        "bedyear",
        "biresus_1",
        "biresus_2",
        "biresus_3",
        "biresus_4",
        "biresus_5",
        "biresus_6",
        "biresus_7",
        "biresus_8",
        "biresus_9",
        "birordr_1",
        "birordr_2",
        "birordr_3",
        "birordr_4",
        "birordr_5",
        "birordr_6",
        "birordr_7",
        "birordr_8",
        "birordr_9",
        "birstat_1",
        "birstat_2",
        "birstat_3",
        "birstat_4",
        "birstat_5",
        "birstat_6",
        "birstat_7",
        "birstat_8",
        "birstat_9",
        "birweit_1",
        "birweit_2",
        "birweit_3",
        "birweit_4",
        "birweit_5",
        "birweit_6",
        "birweit_7",
        "birweit_8",
        "birweit_9",
        "cannet",
        "canreg",
        "carersi",
        "cause",
        "cause_3",
        "cause_4",
        "ccg_gp_practice",
        "ccg_residence",
        "ccg_responsibility",
        "ccg_responsibility_origin",
        "ccg_treatment",
        "ccg_treatment_origin",
        "cdsextdate",
        "cdsverprotid",
        "cdsversion",
        "cendur",
        "censage",
        "censtat",
        "cenward",
        "classpat",
        "cr_gp_practice",
        "cr_residence",
        "cr_treatment",
        "csnum",
        "currward",
        "currward_ons",
        "delchang",
        "delinten",
        "delmeth_1",
        "delmeth_2",
        "delmeth_3",
        "delmeth_4",
        "delmeth_5",
        "delmeth_6",
        "delmeth_7",
        "delmeth_8",
        "delmeth_9",
        "delmeth_d",
        "delonset",
        "delplac_1",
        "delplac_2",
        "delplac_3",
        "delplac_4",
        "delplac_5",
        "delplac_6",
        "delplac_7",
        "delplac_8",
        "delplac_9",
        "delposan",
        "delprean",
        "delstat_1",
        "delstat_2",
        "delstat_3",
        "delstat_4",
        "delstat_5",
        "delstat_6",
        "delstat_7",
        "delstat_8",
        "delstat_9",
        "detdur",
        "detndate",
        "diag_01",
        "diag_02",
        "diag_03",
        "diag_04",
        "diag_05",
        "diag_06",
        "diag_07",
        "diag_08",
        "diag_09",
        "diag_10",
        "diag_11",
        "diag_12",
        "diag_13",
        "diag_14",
        "diag_15",
        "diag_16",
        "diag_17",
        "diag_18",
        "diag_19",
        "diag_20",
        "diag_count",
        "disdate",
        "disdest",
        "disreadydate",
        "dob_cfl",
        "earldatoff",
        "elecdate",
        "elecdur",
        "elecdur_calc",
        "endage",
        "epidur",
        "epiend",
        "epikey",
        "epiorder",
        "epistart",
        "epistat",
        "epitype",
        "ethnos",
        "ethraw",
        "fae",
        "fae_emergency",
        "fce",
        "fde",
        "firstreg",
        "fyear",
        "gestat_1",
        "gestat_2",
        "gestat_3",
        "gestat_4",
        "gestat_5",
        "gestat_6",
        "gestat_7",
        "gestat_8",
        "gestat_9",
        "gortreat",
        "gpprac",
        "gppracha",
        "gppracro",
        "gpprpct",
        "gpprstha",
        "hatreat",
        "hneoind",
        "imd04",
        "imd04c",
        "imd04ed",
        "imd04em",
        "imd04hd",
        "imd04hs",
        "imd04i",
        "imd04ia",
        "imd04ic",
        "imd04le",
        "imd04rk",
        "imd04_decile",
        "intmanig",
        "lsoa01",
        "lsoa11",
        "mainspef",
        "marstat",
        "matage",
        "maternity_episode_type",
        "mentcat",
        "msoa01",
        "msoa11",
        "mydob",
        "neocare",
        "neodur",
        "newnhsno_check",
        "nhsnoind",
        "numbaby",
        "numpreg",
        "numtailb",
        "oacode6",
        "opdate_01",
        "opdate_02",
        "opdate_03",
        "opdate_04",
        "opdate_05",
        "opdate_06",
        "opdate_07",
        "opdate_08",
        "opdate_09",
        "opdate_10",
        "opdate_11",
        "opdate_12",
        "opdate_13",
        "opdate_14",
        "opdate_15",
        "opdate_16",
        "opdate_17",
        "opdate_18",
        "opdate_19",
        "opdate_20",
        "opdate_21",
        "opdate_22",
        "opdate_23",
        "opdate_24",
        "operstat",
        "opertn_01",
        "opertn_02",
        "opertn_03",
        "opertn_04",
        "opertn_05",
        "opertn_06",
        "opertn_07",
        "opertn_08",
        "opertn_09",
        "opertn_10",
        "opertn_11",
        "opertn_12",
        "opertn_13",
        "opertn_14",
        "opertn_15",
        "opertn_16",
        "opertn_17",
        "opertn_18",
        "opertn_19",
        "opertn_20",
        "opertn_21",
        "opertn_22",
        "opertn_23",
        "opertn_24",
        "opertn_count",
        "orgpppid",
        "partyear",
        "pcfound",
        "pcon",
        "pconsult",
        "pcon_ons",
        "pctcode06",
        "pctnhs",
        "pctorig06",
        "pcttreat",
        "posopdur",
        "postdist",
        "postdur",
        "preferer",
        "preggmp",
        "preopdur",
        "primercp",
        "procode",
        "procode3",
        "procode5",
        "procodet",
        "protype",
        "provspnops",
        "purcode",
        "purval",
        "referorg",
        "rescty",
        "rescty_ons",
        "resgor",
        "resgor_ons",
        "resha",
        "resladst",
        "resladst_currward",
        "resladst_ons",
        "respct06",
        "respct_his",
        "resro",
        "resstha06",
        "resstha_his",
        "rotreat",
        "rttperend",
        "rttperstart",
        "rttperstat",
        "rururb_ind",
        "sender",
        "sex",
        "sexbaby_1",
        "sexbaby_2",
        "sexbaby_3",
        "sexbaby_4",
        "sexbaby_5",
        "sexbaby_6",
        "sexbaby_7",
        "sexbaby_8",
        "sexbaby_9",
        "sitetret",
        "spelbgin",
        "speldur",
        "spelend",
        "startage",
        "startage_calc",
        "sthatret",
        "subdate",
        "suscorehrg",
        "sushrg",
        "sushrgvers",
        "suslddate",
        "susrecid",
        "susspellid",
        "tretspef",
        "waitdays",
        "waitlist",
        "well_baby_ind",
    ]
    columns[i] = T.StructField([cols[c] for c in cols])